OnlineRezervacijaBioskopskihKarata/Models/Projection.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web;

namespace OnlineRezervacijaBioskopskihKarata.Models
{
    public class Projection
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Date { get; set; }
        public int TicketCost { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }

        public string GetTicketsSold()
        {
            return Reservations.Count.ToString();
        }

        public string formatReservedSeats()
        {
            StringBuilder sb = new StringBuilder();
            for(int i = 0;i<Reservations.Count;i++)
            {
                sb.Append("\"r" + Reservations.ElementAt(i).Row + "c" + Reservations.ElementAt(i).Column+"\"");
                if (i < Reservations.Count - 1)
                {
                    sb.Append(',');
                }
            }
            return sb.ToString();
        }
    }
}

OnlineRezervacijaBioskopskihKarata/Controllers/ProjectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRezervacijaBioskopskihKarata.Models;

namespace OnlineRezervacijaBioskopskihKarata.Controllers
{
    [Authorize]
    public class ProjectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projections
        public ActionResult Index()
        {
            return View(db.Projections.ToList());
        }
        [AllowAnonymous]
        public ActionResult AllProjections()
        {
            return View(db.Projections.ToList());
        }
        [AllowAnonymous]
        public ActionResult BuyTickets(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projection projection = db.Projections.Find(id);
            if (projection == null)
            {
                return HttpNotFound();
            }
            return View(db.Projections.Include(x => x.Reservations).FirstOrDefault(x=>x.Id==id));
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult BuyTickets(int id, string selectedSeats)
        {
            Projection projection = db.Projections.Find(id);
            List<string> selected = selectedSeats.Split(',').ToList();
            string orderId = Guid.NewGuid().ToString();
            
            foreach (string s in selected)
            {
                int row = Convert.ToInt32( s.Split('r')[1].Split('c')[0]);
                int col = Convert.ToInt32( s.Split('r')[1].Split('c')[1]);
                string guid = Guid.NewGuid().ToString();
                db.Reservations.Add(new Reservation() { 
                    Column=col,
                    Row=row,
                    OrderId=orderId,
                    ProjectionId=id,
                    TicketGuid=guid
                });
            }
            db.SaveChanges();
            return RedirectToAction("ViewReservations",new {transactionId = orderId });
        }
        [AllowAnonymous]
        public ActionResult FindTickets()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult ViewReservations(string transactionId)
        {
            ViewTicketsViewModel model = new ViewTicketsViewModel();
            model.Reservations = db.Reservations.Where(x => x.OrderId == transactionId).ToList();
            model.TransactionId = transactionId;
            model.Projection = db.Reservations.FirstOrDefault(x => x.OrderId == transactionId)?.Projection;
            if (model.Projection != null)
            {
                return View(model);
            }
            return HttpNotFound();
        }

        // GET: Projections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projection projection = db.Projections.Find(id);
            if (projection == null)
            {
                return HttpNotFound();
            }
            return View(projection);
        }

        // GET: Projections/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,StartTime,EndTime,Date,TicketCost")] Projection projection, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                projection.Image = new byte[file.ContentLength];
                file.InputStream.Read(projection.Image, 0, file.ContentLength);
                db.Projections.Add(projection);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projection);
        }

        // GET: Projections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projection projection = db.Projections.Find(id);
            if (projection == null)
            {
                return HttpNotFound();
            }
            
            return View(projection);
        }

        // POST: Projections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,StartTime,EndTime,Date,TicketCost")] Projection projection, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                Projection fromdb = db.Projections.FirstOrDefault(x => x.Id == projection.Id);
                if (file != null)
                {
                    fromdb.Image = new byte[file.ContentLength];
                    file.InputStream.Read(fromdb.Image, 0, file.ContentLength);
                }

                fromdb.Name = projection.Name;
                fromdb.StartTime = projection.StartTime;
                fromdb.EndTime = projection.EndTime;
                fromdb.Date = projection.Date;
                fromdb.TicketCost = projection.TicketCost;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projection);
        }

        // GET: Projections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projection projection = db.Projections.Find(id);
            if (projection == null)
            {
                return HttpNotFound();
            }
            return View(projection);
        }

        // POST: Projections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Projection projection = db.Projections.Find(id);
            db.Projections.Remove(projection);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineRezervacijaBioskopskihKarata/Views/Projections/AllProjections.cshtml
@model IEnumerable<OnlineRezervacijaBioskopskihKarata.Models.Projection>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.incoming_projections}}</h2>

<br />

    @foreach (var item in Model.OrderBy(x => x.Date))
    {
        <div class="card mb-4">
            <div class="row no-gutters">
                <div class="col-lg-4">
                    @if (item.Image != null)
                    {
                        <img src="data:image/jpg;base64,@(Convert.ToBase64String(item.Image))" class="card-img" style="min-height:256px;" />
                    }

                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h3>
                        <hr />
                        <p class="card-text"> <b>{{translation.projection_date}}: </b>@Html.DisplayFor(modelItem => item.Date)</p>
                        <p class="card-text">{{translation.projection_starts_at}} @Html.DisplayFor(modelItem => item.StartTime) {{translation.and_ends_at}} @Html.DisplayFor(modelItem => item.EndTime)</p>
                        <p class="card-text"><b>{{translation.ticket_price}}:</b> @Html.DisplayFor(modelItem => item.TicketCost)din.</p>
                        <button class="btn btn-primary" onclick="document.location.href='/projections/BuyTickets/@Html.DisplayFor(modelItem => item.Id)'">{{translation.button_reserve_tickets}}</button>
                    </div>
                </div>
            </div>
        </div>
    }

   

OnlineRezervacijaBioskopskihKarata/Views/Projections/BuyTickets.cshtml
@model OnlineRezervacijaBioskopskihKarata.Models.Projection
@{
    ViewBag.Title = "BuyTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.buy_tickets}}</h2>
<b>{{translation.select_seats_you_want}}</b>
<input value="@Model.Id" type="hidden" />
<hr />
<center >
    
    <div  style="width:902px; height:502px;  border:1px solid black; text-align:left;">
        <div style="width:500px; height:30px;background-color:dodgerblue; margin-left:201px; text-align:center;">{{translation.movie_cloth}}</div>
        <div style="height:70px;width:100%;"></div>
        <div id="seatContainer"style=" padding:0px; width:900px;height:400px;background-color:whitesmoke;"></div>
        

    </div>
</center>
<br />
<div class="row justify-content-center">
    <div class="col-md-4">
        <h3>{{translation.selected_seats}}:</h3>
        <ul id="selected">

        </ul>
    </div>
    <div class="col-md-4" >
        <form id="form" action="/Projections/buyTickets" method="post" >
            <p>{{translation.ticket_price_is}}: @Model.TicketCost din.</p>
            <p>{{translation.total_price}}: <b id="totalPrice">0</b> din.</p>
            <input type="hidden" value="" id="inputSelected" name="selectedSeats" />
            <button type="button" onclick="checkAndSubmit()" class="btn btn-success btn-lg">{{translation.button_reserve_tickets}}</button>
            <input name="id" value="@Model.Id" type="hidden" />
        </form>
    </div>
</div>
@section Scripts{
    <script>

        var seatcontainer = document.getElementById("seatContainer");
        var startmarker = document.getElementById("startMarker");
        var ticketPrice = @Model.TicketCost;
        var selected = [];
        var reserved = [@Html.Raw(@Model.formatReservedSeats())];
        var pom = "";
        console.log(reserved);
        
        //On ready function
        $(document).ready(function () {
            //Creating grid of seats
            for (row = 1; row <= 8; row++) {
                pom += '<div style="width:900px;height:50px;">';
                for (col = 1; col <= 18; col++) {
                    if (reserved.indexOf('r' + row + 'c' + col) !== -1)
                        pom += '<div style="width:50px; height:50px; display:inline-block; background-image:url(\'/Content/seat-taken.jpg\');"></div>';                    
                    else if(col!=6 && col!=13)
                        pom += '<div id="r' + row + 'c' + col + '" clicked="false"  onclick="chooseSeat(r' + row + 'c' + col + ')" class="seat-vacant"></div>';
                    else
                        pom += '<div style="width:50px; height:50px; display:inline-block; background-image:url(\'/Content/tepih.jpg\');"></div>';
                }
                pom += '</div>'
                seatcontainer.innerHTML += pom;
                pom = "";
            }
           
        });

        function chooseSeat(seat) {
            if (seat.getAttribute("clicked") == "false") {
                //set icon to selected
                seat.setAttribute("clicked", "true");
                seat.classList.add("clicked");

                //add index to selected item array
                selected.push(seat.getAttribute("id"));

                //prints selected seats for user
                printSelectedList();

            } else if (seat.getAttribute("clicked") == "true") {
                //set icon to vacant
                seat.setAttribute("clicked", "false");
                seat.classList.remove("clicked");

                //remove item from selected array
                selected.splice(selected.indexOf(seat.getAttribute("id")), 1);

                //prints selected seats for user
                printSelectedList();
            }

        }

        function printSelectedList() {
            var list = document.getElementById("selected");
            list.innerHTML = "";
            var pom;
            for (i = 0; i < selected.length; i++) {
                pom = selected[i].split('r')[1].split('c');
                list.innerHTML += "<li>Seat " + pom[1] + ", row " + pom[0] + "</li>";

            }
            document.getElementById("totalPrice").innerHTML =  (ticketPrice * selected.length) ;
        }

        function checkAndSubmit() {
            if (selected.length != 0) {
                document.getElementById("inputSelected").setAttribute("value", selected);
                document.getElementById("form").submit();
            }
            else {
                alert("You must select at least one seat!");
            }
        }

    </script>
    }

OnlineRezervacijaBioskopskihKarata/Views/Projections/Create.cshtml
@model OnlineRezervacijaBioskopskihKarata.Models.Projection

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.create_new_projection}}</h2>


@using (Html.BeginForm("Create", "Projections", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            {{translation.projection_name}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.start_time}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.end_time}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.projection_date}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @id = "datepicker", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.ticket_price}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketCost, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" ng-controller="preview-ctrl">
            {{translation.image}}
            <div class="col-md-10">
                <input type="file" onchange="angular.element(this).scope().SelectFile(event)" name="file" accept="image/*" /><br /><br />
                <img ng-src="{{PreviewImage}}" ng-show="PreviewImage != null" alt="" style="height:200px;" />
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <br />
                <button type="submit" class="btn btn-primary">{{translation.create_new_projection}}</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("{{translation.back_to_projections_list}}", "Index")
</div>

@section Scripts {
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#datepicker").datepicker({ dateFormat: 'dd.mm.yy.' });
        });
    </script>
    <script>
        app.controller("preview-ctrl", function ($scope) {
            $scope.SelectFile = function (e) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $scope.PreviewImage = e.target.result;
                    $scope.$apply();
                };

                reader.readAsDataURL(e.target.files[0]);
            };
        });
    </script>
}

OnlineRezervacijaBioskopskihKarata/Views/Projections/Delete.cshtml
@model OnlineRezervacijaBioskopskihKarata.Models.Projection

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.delete_projection_header}}</h2>

<h5>{{translation.are_you_sure_delete}}</h5>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            {{translation.projection_name}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            {{translation.start_time}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            {{translation.end_time}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            {{translation.projection_date}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            {{translation.ticket_price}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketCost)
        </dd>
        <dt>
            {{translation.image}}
        </dt>
        <dd>
            @if (Model.Image != null)
            {
                <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Image))" alt="@Model.Name"  style="max-height:300px;"/>

            }

        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="{{translation.delete_projection}}" class="btn btn-primary"/> |
            @Html.ActionLink("{{translation.back_to_projections_list}}", "Index")
        </div>
    }
    </div>

OnlineRezervacijaBioskopskihKarata/Views/Projections/Details.cshtml
@model OnlineRezervacijaBioskopskihKarata.Models.Projection

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.projection_details}}</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            {{translation.projection_name}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            {{translation.start_time}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            {{translation.end_time}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            {{translation.projection_date}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            {{translation.ticket_price}}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketCost)
        </dd>
        <dt>
            {{translation.image}}
        </dt>
        <dd>
            @if (Model.Image != null)
            {
            <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Image))" alt="@Model.Name" style="max-height:300px;" />

            }

        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("{{translation.edit_projection}}", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("{{translation.back_to_projections_list}}", "Index")
</p>

OnlineRezervacijaBioskopskihKarata/Views/Projections/Edit.cshtml
@model OnlineRezervacijaBioskopskihKarata.Models.Projection

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.edit_projection}}</h2>


@using (Html.BeginForm("Edit", "Projections", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            {{translation.projection_name}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.start_time}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.end_time}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.projection_date}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @id = "datepicker", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            {{translation.ticket_price}}
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketCost, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" ng-controller="preview-ctrl">
            {{translation.image}}
            <div class="col-md-10">
                <input type="file" onchange="angular.element(this).scope().SelectFile(event)" name="file" accept="image/*" /><br /><br />
                <img ng-src="{{PreviewImage}}" ng-show="PreviewImage != null" alt="" style="height:200px;" />
                @if(Model.Image != null){
                <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Image))" ng-show="PreviewImage == null" alt="@Model.Name" style="max-height:200px;" />
                }
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="{{translation.save_changes}}" class="btn btn-primary"  />
                <img class="thumb" ng-src="{{img}}" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("{{translation.back_to_projections_list}}", "Index")
</div>

@section Scripts {

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#datepicker").datepicker({ dateFormat: 'dd.mm.yy.' });
        });
    </script>
    <script>
        app.controller("preview-ctrl", function ($scope) {
            $scope.SelectFile = function (e) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $scope.PreviewImage = e.target.result;
                    $scope.$apply();
                };

                reader.readAsDataURL(e.target.files[0]);
            };
        });
    </script>
}


    

OnlineRezervacijaBioskopskihKarata/Views/Projections/FindTickets.cshtml
@{
    ViewBag.Title = "FindTickets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.find_tickets}}</h2>

<h5>{{translation.find_tickets_by_transaction_number}}</h5>
<hr />

<form action="/projections/ViewReservations" method="get">
    {{translation.transaction_number}}
    <input name="transactionId" type="text" class="form-control input-lg" placeholder="{{translation.transaction_number}}" /><br />
    <button type="submit" class="btn btn-primary">{{translation.find_tickets}}</button>
</form>

OnlineRezervacijaBioskopskihKarata/Views/Projections/ViewReservations.cshtml
@model OnlineRezervacijaBioskopskihKarata.Models.ViewTicketsViewModel
@{
    ViewBag.Title = "My tickets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>{{translation.reservations_made_in_transaction}}: @Model.TransactionId</h2>
<b>{{translation.take_picture_or_print}}</b>
<br />
<br />

@foreach(var res in Model.Reservations)
{

    
    <div class="card bg-light mb-3" style="width: 900px">
        <div class="card-header" style="font-weight:300; font-size:12pt;">@res.TicketGuid</div>
        <div class="card-body">
            <h5 class="card-title" style="font-weight:500; font-size:16pt;">@Model.Projection.Name</h5>
            <hr />
            <p class="card-text" style="font-weight:400; font-size:14pt;">
                {{translation.projection_date}}: @Model.Projection.Date<br />
                {{translation.projection_starts_at}}: @Model.Projection.StartTime   {{translation.and_ends_at}}: @Model.Projection.EndTime<br /><br />

                {{translation.seat}} @res.Column {{translation.row}} @res.Row

            </p>
        </div>
    </div>

}

<button class="btn btn-primary" onclick="document.location.href='/'">{{translation.back_to_index}}</button>